# Generated by Django 5.1.4 on 2024-12-26 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CB', 'Computer Basics'), ('WD', 'Web Development'), ('CS', 'Cyber Security'), ('MCE', 'Mechanical and Civil Engineering')], default='CB', max_length=3)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('modules', models.TextField()),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(upload_to='courses/', verbose_name='Main Image')),
                ('additional_images', models.ImageField(blank=True, help_text='You can upload more images (optional)', max_length=200, null=True, upload_to='courses/additional/', verbose_name='Additional Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.coursecategory')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
