# Generated by Django 5.1.4 on 2024-12-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_coursecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
